GENCCODE_ASSEMBLY_TYPE=-a gcc
SO=so
SOBJ=so
A=a
LIBPREFIX=lib
LIB_EXT_ORDER=.58.2
COMPILE=/tmp/build/80754af9/icu_1588025984309/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/hm1412/anaconda3/envs/CUTandTAG/include -D_REENTRANT  -DU_HAVE_ELF_H=1 -DU_HAVE_ATOMIC=1 -DU_HAVE_STRTOD_L=1  -DU_ATTRIBUTE_DEPRECATED= -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/hm1412/anaconda3/envs/CUTandTAG/include -fdebug-prefix-map=/tmp/build/80754af9/icu_1588025984309/work=/usr/local/src/conda/icu-58.2 -fdebug-prefix-map=/home/hm1412/anaconda3/envs/CUTandTAG=/usr/local/src/conda-prefix -std=c99 -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings   -c
LIBFLAGS=-I/home/hm1412/anaconda3/envs/CUTandTAG/include -DPIC -fPIC
GENLIB=/tmp/build/80754af9/icu_1588025984309/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/hm1412/anaconda3/envs/CUTandTAG/include -fdebug-prefix-map=/tmp/build/80754af9/icu_1588025984309/work=/usr/local/src/conda/icu-58.2 -fdebug-prefix-map=/home/hm1412/anaconda3/envs/CUTandTAG=/usr/local/src/conda-prefix -std=c99 -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings   -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/hm1412/anaconda3/envs/CUTandTAG/lib -Wl,-rpath-link,/home/hm1412/anaconda3/envs/CUTandTAG/lib -L/home/hm1412/anaconda3/envs/CUTandTAG/lib  -shared -Wl,-Bsymbolic
LDICUDTFLAGS=-nodefaultlibs -nostdlib
LD_SONAME=-Wl,-soname -Wl,
RPATH_FLAGS=
BIR_LDFLAGS=-Wl,-Bsymbolic
AR=/tmp/build/80754af9/icu_1588025984309/_build_env/bin/x86_64-conda_cos6-linux-gnu-ar
ARFLAGS=r
RANLIB=/tmp/build/80754af9/icu_1588025984309/_build_env/bin/x86_64-conda_cos6-linux-gnu-ranlib
INSTALL_CMD=/usr/bin/install -c
